title = "Peak Scale"

defaultContentLanguage = "de"

[languages]
[languages.de]
contentDir = "content/de"
languageCode = "de-ch"
[languages.de.params]
description = "Cloud Native Experten"
privacy = "Datenschutz"
legalnotice = "Impressum"
[languages.de.params.hero]
hero__title = "Cloud Native Experten"
hero__description = """Bei Peak Scale sind wir überzeugt, dass IT-Architektur dem steten Wandel unterliegt.
    Deshalb bauen wir auf pragmatische und evolutionäre Ansätze bei unseren Konzepten.
    Gerne unterstützen und beraten wir mit Dienstleistungen in den Bereichen Architektur, Engineering,
    Trainings und Assessments im Umfeld von modernen, Cloud Native-basierten Infrastrukturen."""
[[languages.de.menus.main]]
identifier = "services"
name = "Angebot"
pageRef = "/services"
weight = 2
[[languages.de.menus.main]]
identifier = "about"
name = "Über uns"
pageRef = "/about"
weight = 3
[[languages.de.menus.main]]
identifier = "team"
name = "Team"
pageRef = "/team"
weight = 4

[languages.en]
contentDir = "content/en"
languageCode = "en-en"
[languages.en.params]
description = "Cloud Native Experts"
privacy = "Privacy"
legalnotice = "Legal Notice"
[languages.en.params.hero]
hero__title = "Cloud Native Experts"
hero__description = """At Peak Scale, we are convinced that IT architecture is subject to constant change.
    That is why we rely on pragmatic and evolutionary approaches.
    We are happy to support and advise with services in the areas of architecture, engineering,
    training, and assessments in the context of modern, cloud native-based infrastructures."""
[[languages.en.menus.main]]
identifier = "services"
name = "Services"
pageRef = "/services"
weight = 2
[[languages.en.menus.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 3
[[languages.en.menus.main]]
identifier = "team"
name = "Team"
pageRef = "/team"
weight = 4

[params]
logo = "/images/logos/peakscale.svg"
logoDark = "/images/logos/peakscale_dark.svg"
author = "Peak Scale"
imageSocial = "/images/logos/peakscale_social.png"

[params.plausible]
enable = true
domain = "peakscale.ch"

#-------------------------------
# Footer Settings
# Other icons can be found at https://ionicons.com/v4/
[[params.social]]
icon = "logo-linkedin"
name = "LinkedIn"
link = "https://www.linkedin.com/company/peakscale/"
color = "#0580c4"


#-------------------------------
# Contact Settings
[params.contact]
email = "mjvlykdz" # Add your Formspree form_id for contant form

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = false
